# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Commit files
        run: |
          git add .
          git config --local user.email "1523838521@qq.com"
          git config --local user.name "quarksb"
          git commit -m "build github page" -a
      - name: Deploy
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
